import { createDuckDBValueConverter } from './createDuckDBValueConverter';
import { DuckDBTypeId } from './DuckDBTypeId';
import { DuckDBValueConverter } from './DuckDBValueConverter';
import {
  arrayFromArrayValue,
  arrayFromListValue,
  bigintFromBigIntValue,
  bigintFromTimeValue,
  booleanFromValue,
  bytesFromBitValue,
  bytesFromBlobValue,
  dateFromDateValue,
  dateFromTimestampMillisecondsValue,
  dateFromTimestampNanosecondsValue,
  dateFromTimestampSecondsValue,
  dateFromTimestampTZValue,
  dateFromTimestampValue,
  doubleFromDecimalValue,
  nullConverter,
  numberFromValue,
  objectArrayFromMapValue,
  objectFromIntervalValue,
  objectFromStructValue,
  objectFromTimeTZValue,
  objectFromUnionValue,
  stringFromValue,
  unsupportedConverter,
} from './DuckDBValueConverters';
import { JS } from './JS';

const JSConvertersByTypeId: Record<DuckDBTypeId, DuckDBValueConverter<JS>> = {
  [DuckDBTypeId.INVALID]: unsupportedConverter,
  [DuckDBTypeId.BOOLEAN]: booleanFromValue,
  [DuckDBTypeId.TINYINT]: numberFromValue,
  [DuckDBTypeId.SMALLINT]: numberFromValue,
  [DuckDBTypeId.INTEGER]: numberFromValue,
  [DuckDBTypeId.BIGINT]: bigintFromBigIntValue,
  [DuckDBTypeId.UTINYINT]: numberFromValue,
  [DuckDBTypeId.USMALLINT]: numberFromValue,
  [DuckDBTypeId.UINTEGER]: numberFromValue,
  [DuckDBTypeId.UBIGINT]: bigintFromBigIntValue,
  [DuckDBTypeId.FLOAT]: numberFromValue,
  [DuckDBTypeId.DOUBLE]: numberFromValue,
  [DuckDBTypeId.TIMESTAMP]: dateFromTimestampValue,
  [DuckDBTypeId.DATE]: dateFromDateValue,
  [DuckDBTypeId.TIME]: bigintFromTimeValue,
  [DuckDBTypeId.INTERVAL]: objectFromIntervalValue,
  [DuckDBTypeId.HUGEINT]: bigintFromBigIntValue,
  [DuckDBTypeId.UHUGEINT]: bigintFromBigIntValue,
  [DuckDBTypeId.VARCHAR]: stringFromValue,
  [DuckDBTypeId.BLOB]: bytesFromBlobValue,
  [DuckDBTypeId.DECIMAL]: doubleFromDecimalValue,
  [DuckDBTypeId.TIMESTAMP_S]: dateFromTimestampSecondsValue,
  [DuckDBTypeId.TIMESTAMP_MS]: dateFromTimestampMillisecondsValue,
  [DuckDBTypeId.TIMESTAMP_NS]: dateFromTimestampNanosecondsValue,
  [DuckDBTypeId.ENUM]: stringFromValue,
  [DuckDBTypeId.LIST]: arrayFromListValue,
  [DuckDBTypeId.STRUCT]: objectFromStructValue,
  [DuckDBTypeId.MAP]: objectArrayFromMapValue,
  [DuckDBTypeId.ARRAY]: arrayFromArrayValue,
  [DuckDBTypeId.UUID]: stringFromValue,
  [DuckDBTypeId.UNION]: objectFromUnionValue,
  [DuckDBTypeId.BIT]: bytesFromBitValue,
  [DuckDBTypeId.TIME_TZ]: objectFromTimeTZValue,
  [DuckDBTypeId.TIMESTAMP_TZ]: dateFromTimestampTZValue,
  [DuckDBTypeId.ANY]: unsupportedConverter,
  [DuckDBTypeId.VARINT]: bigintFromBigIntValue,
  [DuckDBTypeId.SQLNULL]: nullConverter,
};

export const JSDuckDBValueConverter =
  createDuckDBValueConverter(JSConvertersByTypeId);
